[options]
addons_path = /mnt/extra-addons

admin_passwd = admin123
db_name = cinagrodb
db_host = dpg-d8rb2237uimc73evcbe0-a
db_port = 5432
db_user = cinagrodb_user
db_password = pe8hcSAhJWfzQoFy29abnzbFMZg0GdNC
log_level = info